print('hi, what is your first name')
first_name = input()
print('enter your last name')
last_name = input()
print("what is your DOB")
dob = input()
print('are you a uk resident. please answer yes or no')
uk_resident = input()
print(f'hello {first_name} {last_name} {dob} uk resident: {uk_resident}')